---
- name: Install GitHub CLI from the GitHub apt repository
  become: true
  block:
    - name: Add the GitHub CLI apt repository
      ansible.builtin.deb822_repository:
        name: "{{ gh_apt_repo_name }}"
        state: present
        types: deb
        uris: "{{ gh_apt_repo_url }}"
        suites: "{{ gh_apt_repo_channel }}"
        components:
          - main
        signed_by: "{{ gh_apt_keyring_url }}"

    - name: Install GitHub CLI package
      ansible.builtin.apt:
        name: "{{ gh_package_name }}"
        state: "{{ gh_package_state }}"
        update_cache: true
