---
galaxy_info:
  author: Krishana Pal Singh Chouhan
  description: Install HashiCorp Vagrant on macOS.
  company: kpsinghchouhan
  license: GPL-2.0-or-later
  min_ansible_version: "2.15"

  platforms:
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - vagrant
    - hashicorp
    - virtualization
    - developer
    - macos

dependencies: []
